DROP TABLE IF EXISTS RA CASCADE;
DROP TABLE IF EXISTS Temperatura CASCADE;
DROP TABLE IF EXISTS Umidade CASCADE;
DROP TABLE IF EXISTS Precipitacao CASCADE;
DROP TABLE IF EXISTS Pressao_Atm CASCADE;
DROP TABLE IF EXISTS Ventos CASCADE;
DROP TABLE IF EXISTS Nebulosidade CASCADE;
DROP TABLE IF EXISTS Est_Nebulosidade CASCADE;
DROP TABLE IF EXISTS Insolacao CASCADE;
DROP TABLE IF EXISTS Evaporacao CASCADE;
DROP TABLE IF EXISTS Bairro CASCADE;
DROP TABLE IF EXISTS Alagamento CASCADE;

CREATE TABLE RA
    (codRA      INTEGER UNSIGNED PRIMARY KEY,
    nome        VARCHAR(30) NOT NULL,
    populacao   INTEGER UNSIGNED,
    data_criacao DATE);

CREATE TABLE Temperatura
    (mes_Ano    VARCHAR(7),
    codRA       INTEGER REFERENCES RA(codRA),
    temp_Med    INTEGER NOT NULL,
    temp_Max    INTEGER NOT NULL,
    temp_Min    INTEGER NOT NULL,
    id_temp		INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Umidade
    (mes_Ano    VARCHAR(7),
    codRA       INTEGER REFERENCES RA(codRA),
    umi_Med     INTEGER UNSIGNED NOT NULL,
    umi_Max     INTEGER UNSIGNED NOT NULL,
    umi_Min     INTEGER UNSIGNED NOT NULL,
	id_umi 		INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Precipitacao
    (mes    VARCHAR(9) NOT NULL,
    codRA       INTEGER REFERENCES RA(codRA),
    precipit    FLOAT UNSIGNED NOT NULL,
	id_precipt  INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Pressao_Atm
    (mes    	VARCHAR(9) NOT NULL,
    codRA       INTEGER REFERENCES RA(codRA),
    patm_Med    FLOAT UNSIGNED NOT NULL,
	id_patm INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Ventos
    (mes    VARCHAR(9) NOT NULL,
    codRA       INTEGER REFERENCES RA(codRA),
    vel_Med     FLOAT UNSIGNED NOT NULL,
	id_vel INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Est_Nebulosidade
    (codNeb     INTEGER UNSIGNED PRIMARY KEY,
    nome        VARCHAR(15) NOT NULL);

CREATE TABLE Nebulosidade
    (mes    VARCHAR(9) NOT NULL,
    codRA       INTEGER REFERENCES RA(codRA),
    ceu_encoberto   FLOAT UNSIGNED NOT NULL,
	codNeb     INTEGER REFERENCES Est_Nebulosidade(codNeb),
	id_neb INTEGER PRIMARY KEY AUTO_INCREMENT);
    
CREATE TABLE Insolacao
    (mes 		VARCHAR(9) NOT NULL,
    codRA		INTEGER REFERENCES RA(codRA),
    ins_med 	FLOAT UNSIGNED NOT NULL,
    id_ins		INTEGER PRIMARY KEY AUTO_INCREMENT);
    
CREATE TABLE Evaporacao
    (mes		VARCHAR(9) NOT NULL,
    codRA		INTEGER REFERENCES RA(codRA),
    evap_med	FLOAT UNSIGNED NOT NULL,
    id_evap		INTEGER PRIMARY KEY AUTO_INCREMENT);

CREATE TABLE Bairro
    (codBairro INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    codRA      INTEGER REFERENCES RA(codRA),
    nome       VARCHAR(30) NOT NULL,
    populacao  INTEGER UNSIGNED);

CREATE TABLE Alagamento
    (codAlagamento INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    codBairro  INTEGER REFERENCES Bairro(codBairro),
    dia 	   DATE NOT NULL,
    rua        VARCHAR(30) NOT NULL,
    inicio	   VARCHAR(5),
    fim		   VARCHAR(5),
    imagem     BLOB);
